/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemaEnvios.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import sistemaEnvios.dao.EnvioDAO;
import sistemaEnvios.dao.ObjetoDAO;
import sistemaEnvios.dao.UsuarioDAO;
import sistemaEnvios.model.Envio;
import sistemaEnvios.model.Frete;
import sistemaEnvios.model.FreteNormal;
import sistemaEnvios.model.FreteSedex;
import sistemaEnvios.model.Objeto;
import sistemaEnvios.model.Pessoa;
import sistemaEnvios.model.Usuario;


/**
 *
 * @author mayara
 */
public class TelaEnvios extends javax.swing.JFrame {

    /**
     * Creates new form TelaEnvios
     */
    public TelaEnvios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLimpar = new javax.swing.JButton();
        lbEnviarObjeto = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        lbTituloRemetente = new javax.swing.JLabel();
        txtCodigoRemetente = new javax.swing.JTextField();
        lbCodigoRemetente = new javax.swing.JLabel();
        lbNomeRemetente = new javax.swing.JLabel();
        txtNomeRemetente = new javax.swing.JTextField();
        lbTituloDestinatario = new javax.swing.JLabel();
        txtCodigoDestinatario = new javax.swing.JTextField();
        lbCodigoDestinatario = new javax.swing.JLabel();
        lbNomeDestinatario = new javax.swing.JLabel();
        txtNomeDestinatario = new javax.swing.JTextField();
        lbNomeDestinatario1 = new javax.swing.JLabel();
        txtNomeObjeto = new javax.swing.JTextField();
        lbTituloObjeto = new javax.swing.JLabel();
        txtCodigoObjeto = new javax.swing.JTextField();
        lbCodigoDestinatario1 = new javax.swing.JLabel();
        lbFrete = new javax.swing.JLabel();
        txtCidadeRemetente = new javax.swing.JTextField();
        lbBairro = new javax.swing.JLabel();
        txtBairroRemetente = new javax.swing.JTextField();
        lbNumeroRemetente = new javax.swing.JLabel();
        txtNumeroRemetente = new javax.swing.JTextField();
        lbEstadoRemetente = new javax.swing.JLabel();
        lbLogradouro = new javax.swing.JLabel();
        txtEstadoRemetente = new javax.swing.JTextField();
        txtLogradouroRemetente = new javax.swing.JTextField();
        lbCepRemetente = new javax.swing.JLabel();
        txtCepRemetente = new javax.swing.JTextField();
        lbCidade = new javax.swing.JLabel();
        txtCidadeDestinatario = new javax.swing.JTextField();
        lbBairroDestinatario = new javax.swing.JLabel();
        txtBairroDestinatario = new javax.swing.JTextField();
        lbNumeroDestinatario = new javax.swing.JLabel();
        txtEstadoDestinatario = new javax.swing.JTextField();
        lbEstadoDestinatario = new javax.swing.JLabel();
        lbLogradouro1 = new javax.swing.JLabel();
        txtNumeroDestarinario = new javax.swing.JTextField();
        txtLogradouroDestinatario = new javax.swing.JTextField();
        lbCepDestinatario = new javax.swing.JLabel();
        txtCepDestinatario = new javax.swing.JTextField();
        lbCidadeDestinatario = new javax.swing.JLabel();
        btnBuscarRemetente = new javax.swing.JButton();
        btnBuscarDestinatario = new javax.swing.JButton();
        btnBuscarObjeto = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        cbStatus = new javax.swing.JComboBox<>();
        lbStatus = new javax.swing.JLabel();
        cbTipoFrete = new javax.swing.JComboBox<>();
        txtValorFrete = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lbEnviarObjeto.setFont(new java.awt.Font("Liberation Mono", 1, 18)); // NOI18N
        lbEnviarObjeto.setText("Enviar Objeto");

        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lbTituloRemetente.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lbTituloRemetente.setText("REMETENTE:");

        txtCodigoRemetente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoRemetenteActionPerformed(evt);
            }
        });

        lbCodigoRemetente.setText("Código:*");

        lbNomeRemetente.setText("Nome do remetente:*");

        lbTituloDestinatario.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lbTituloDestinatario.setText("DESTINATÁRIO:");

        txtCodigoDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoDestinatarioActionPerformed(evt);
            }
        });

        lbCodigoDestinatario.setText("Código:*");

        lbNomeDestinatario.setText("Nome do destinatário:*");

        lbNomeDestinatario1.setText("Nome do objeto:*");

        lbTituloObjeto.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lbTituloObjeto.setText("OBJETO:");

        lbCodigoDestinatario1.setText("Código:*");

        lbFrete.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lbFrete.setText("FRETE:");

        lbBairro.setText("Bairro:*");

        lbNumeroRemetente.setText("Nº:*");

        txtNumeroRemetente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroRemetenteActionPerformed(evt);
            }
        });

        lbEstadoRemetente.setText("Estado:*");

        lbLogradouro.setText("Logradouro:*");

        txtEstadoRemetente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoRemetenteActionPerformed(evt);
            }
        });

        lbCepRemetente.setText("CEP:*");

        lbCidade.setText("Cidade:*");

        lbBairroDestinatario.setText("Bairro:*");

        lbNumeroDestinatario.setText("Nº:*");

        txtEstadoDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoDestinatarioActionPerformed(evt);
            }
        });

        lbEstadoDestinatario.setText("Estado:*");

        lbLogradouro1.setText("Logradouro:*");

        txtNumeroDestarinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDestarinarioActionPerformed(evt);
            }
        });

        lbCepDestinatario.setText("CEP:*");

        lbCidadeDestinatario.setText("Cidade:*");

        btnBuscarRemetente.setText(" Buscar");
        btnBuscarRemetente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRemetenteActionPerformed(evt);
            }
        });

        btnBuscarDestinatario.setText("Buscar");
        btnBuscarDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDestinatarioActionPerformed(evt);
            }
        });

        btnBuscarObjeto.setText("Buscar");
        btnBuscarObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarObjetoActionPerformed(evt);
            }
        });

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enviado", "Em trânsito", "Entregue" }));

        lbStatus.setText("Status");

        cbTipoFrete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Sedex" }));
        cbTipoFrete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoFreteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbEnviarObjeto))
                    .addComponent(lbNomeRemetente)
                    .addComponent(txtNomeRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLogradouro)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBairroRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbBairro))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumeroRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbNumeroRemetente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEstadoRemetente)
                                    .addComponent(txtEstadoRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbCepRemetente)
                                .addComponent(txtCepRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lbCidade)
                    .addComponent(txtLogradouroRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidadeRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTituloRemetente)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodigoRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarRemetente))
                            .addComponent(lbCodigoRemetente)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbLogradouro1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 2, Short.MAX_VALUE)
                                        .addComponent(txtLogradouroDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCepDestinatario)
                                    .addComponent(txtCepDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodigoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarDestinatario))
                            .addComponent(txtNomeDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTituloDestinatario)
                            .addComponent(lbCodigoDestinatario)
                            .addComponent(lbNomeDestinatario)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbNomeDestinatario1)
                                            .addComponent(txtNomeObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lbTituloObjeto, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbCodigoDestinatario1)
                                                .addGap(124, 124, 124))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(txtCodigoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnBuscarObjeto)))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbStatus)
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbFrete)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbTipoFrete, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(txtValorFrete, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCidadeDestinatario)
                                    .addComponent(txtCidadeDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbBairroDestinatario)
                                    .addComponent(txtBairroDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumeroDestarinario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbNumeroDestinatario))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEstadoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstadoDestinatario)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbEnviarObjeto)
                .addGap(18, 18, 18)
                .addComponent(lbTituloRemetente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCodigoRemetente)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRemetente))
                .addGap(12, 12, 12)
                .addComponent(lbNomeRemetente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomeRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogradouro)
                    .addComponent(lbCepRemetente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogradouroRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCepRemetente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCidade)
                    .addComponent(lbNumeroRemetente)
                    .addComponent(lbEstadoRemetente)
                    .addComponent(lbBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBairroRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCidadeRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumeroRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEstadoRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lbTituloDestinatario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbCodigoDestinatario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDestinatario))
                .addGap(18, 18, 18)
                .addComponent(lbNomeDestinatario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNomeDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCepDestinatario)
                            .addComponent(lbLogradouro1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCepDestinatario)
                            .addComponent(txtLogradouroDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 126, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNumeroDestinatario)
                            .addComponent(lbEstadoDestinatario)
                            .addComponent(lbBairroDestinatario)
                            .addComponent(lbCidadeDestinatario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEstadoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroDestarinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBairroDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCidadeDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTituloObjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbCodigoDestinatario1)
                                    .addComponent(lbStatus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCodigoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuscarObjeto)
                                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lbNomeDestinatario1)
                                .addGap(4, 4, 4)
                                .addComponent(txtNomeObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbFrete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtValorFrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTipoFrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)))
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpar)
                            .addComponent(btnSalvar))
                        .addGap(57, 57, 57))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       int codigoRemetente = Integer.parseInt(txtCodigoRemetente.getText());
       int codigoDestinatario = Integer.parseInt(txtCodigoDestinatario.getText());
       int codigoObjeto = Integer.parseInt(txtCodigoObjeto.getText());
       String status = (String) cbStatus.getSelectedItem();

       UsuarioDAO usuariodao = new UsuarioDAO();
       ObjetoDAO objetodao = new ObjetoDAO();
       EnvioDAO enviodao = new EnvioDAO();
       
       Usuario remetente = usuariodao.buscarUsuario(codigoRemetente);
       Usuario destinatario = usuariodao.buscarUsuario(codigoDestinatario);
       Objeto objeto = objetodao.buscarObjeto(codigoObjeto);
       
        double valorFrete = 0;
        if (cbTipoFrete.getSelectedItem().toString().equals("Normal")) {
            Frete frete = new FreteNormal();
            valorFrete = frete.calculaFrete();
        } else if (cbTipoFrete.getSelectedItem().toString().equals("Sedex")) {
            Frete frete = new FreteSedex();
            valorFrete = frete.calculaFrete();
        }
       
       Envio envio = new Envio(
               remetente,
               destinatario,
               objeto,
               status,
               valorFrete);
       enviodao.salvarEnvio(envio);
       JOptionPane.showMessageDialog(null, "Envio realizado com sucesso!");
        enviodao.imprimirListaEnvios();
       
       
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtCodigoRemetenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoRemetenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoRemetenteActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
    txtBairroDestinatario.setText("");
    txtBairroRemetente.setText("");
    txtCepDestinatario.setText("");
    txtCepRemetente.setText("");
    txtCidadeDestinatario.setText("");
    txtCidadeRemetente.setText("");
    txtCodigoDestinatario.setText("");
    txtCodigoObjeto.setText("");
    txtCodigoRemetente.setText("");
    txtEstadoDestinatario.setText("");
    txtEstadoRemetente.setText("");
    txtLogradouroDestinatario.setText("");
    txtLogradouroRemetente.setText("");
    txtNomeDestinatario.setText("");
    txtNomeObjeto.setText("");
    txtNomeRemetente.setText("");
    txtNumeroDestarinario.setText("");
    txtNumeroRemetente.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtNumeroRemetenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroRemetenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroRemetenteActionPerformed

    private void txtEstadoRemetenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoRemetenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoRemetenteActionPerformed

    private void txtEstadoDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoDestinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoDestinatarioActionPerformed

    private void txtNumeroDestarinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDestarinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDestarinarioActionPerformed

    private void btnBuscarRemetenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRemetenteActionPerformed
       int codigoRemetente = Integer.parseInt(txtCodigoRemetente.getText());
       UsuarioDAO usuariodao = new UsuarioDAO();
       
       Usuario usuario = usuariodao.buscarUsuario(codigoRemetente);
         txtBairroRemetente.setText(usuario.getBairro());
         txtCepRemetente.setText(usuario.getCEP());
         txtCidadeRemetente.setText(usuario.getCidade());
         txtEstadoRemetente.setText(usuario.getEstado());
         txtLogradouroRemetente.setText(usuario.getLogradouro());
         txtNomeRemetente.setText(usuario.getNome());
         txtNumeroRemetente.setText(usuario.getNumero());
    }//GEN-LAST:event_btnBuscarRemetenteActionPerformed

    private void txtCodigoDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDestinatarioActionPerformed
    }//GEN-LAST:event_txtCodigoDestinatarioActionPerformed

    private void btnBuscarObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarObjetoActionPerformed
        int codigoObjeto = Integer.parseInt(txtCodigoObjeto.getText());
        ObjetoDAO objetodao = new ObjetoDAO();
       
       Objeto objeto = objetodao.buscarObjeto(codigoObjeto);
        txtNomeObjeto.setText(objeto.getNome());
    }//GEN-LAST:event_btnBuscarObjetoActionPerformed

    private void btnBuscarDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDestinatarioActionPerformed
     int codigoDestinatario = Integer.parseInt(txtCodigoDestinatario.getText());
       UsuarioDAO usuariodao = new UsuarioDAO();
       
       Usuario usuario = usuariodao.buscarUsuario(codigoDestinatario);
         txtBairroDestinatario.setText(usuario.getBairro());
         txtCepDestinatario.setText(usuario.getCEP());
         txtCidadeDestinatario.setText(usuario.getCidade());
         txtEstadoDestinatario.setText(usuario.getEstado());
         txtLogradouroDestinatario.setText(usuario.getLogradouro());
         txtNomeDestinatario.setText(usuario.getNome());
         txtNumeroDestarinario.setText(usuario.getNumero());
    }//GEN-LAST:event_btnBuscarDestinatarioActionPerformed

    private void cbTipoFreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoFreteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoFreteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEnvios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEnvios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEnvios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEnvios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEnvios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarDestinatario;
    private javax.swing.JButton btnBuscarObjeto;
    private javax.swing.JButton btnBuscarRemetente;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JComboBox<String> cbTipoFrete;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbBairroDestinatario;
    private javax.swing.JLabel lbCepDestinatario;
    private javax.swing.JLabel lbCepRemetente;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbCidadeDestinatario;
    private javax.swing.JLabel lbCodigoDestinatario;
    private javax.swing.JLabel lbCodigoDestinatario1;
    private javax.swing.JLabel lbCodigoRemetente;
    private javax.swing.JLabel lbEnviarObjeto;
    private javax.swing.JLabel lbEstadoDestinatario;
    private javax.swing.JLabel lbEstadoRemetente;
    private javax.swing.JLabel lbFrete;
    private javax.swing.JLabel lbLogradouro;
    private javax.swing.JLabel lbLogradouro1;
    private javax.swing.JLabel lbNomeDestinatario;
    private javax.swing.JLabel lbNomeDestinatario1;
    private javax.swing.JLabel lbNomeRemetente;
    private javax.swing.JLabel lbNumeroDestinatario;
    private javax.swing.JLabel lbNumeroRemetente;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTituloDestinatario;
    private javax.swing.JLabel lbTituloObjeto;
    private javax.swing.JLabel lbTituloRemetente;
    private javax.swing.JTextField txtBairroDestinatario;
    private javax.swing.JTextField txtBairroRemetente;
    private javax.swing.JTextField txtCepDestinatario;
    private javax.swing.JTextField txtCepRemetente;
    private javax.swing.JTextField txtCidadeDestinatario;
    private javax.swing.JTextField txtCidadeRemetente;
    private javax.swing.JTextField txtCodigoDestinatario;
    private javax.swing.JTextField txtCodigoObjeto;
    private javax.swing.JTextField txtCodigoRemetente;
    private javax.swing.JTextField txtEstadoDestinatario;
    private javax.swing.JTextField txtEstadoRemetente;
    private javax.swing.JTextField txtLogradouroDestinatario;
    private javax.swing.JTextField txtLogradouroRemetente;
    private javax.swing.JTextField txtNomeDestinatario;
    private javax.swing.JTextField txtNomeObjeto;
    private javax.swing.JTextField txtNomeRemetente;
    private javax.swing.JTextField txtNumeroDestarinario;
    private javax.swing.JTextField txtNumeroRemetente;
    private javax.swing.JTextField txtValorFrete;
    // End of variables declaration//GEN-END:variables
}
